version: '2'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.45.0
    ports:
      - '16686:16686'
    networks:
      - nginx_otel_net

  collector:
    # image: otel/opentelemetry-collector:latest
    image: otel/opentelemetry-collector:0.77.0
    command:
      - --config=/etc/otel-collector-config.yaml
    volumes:
      - ./conf.d/collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - nginx_otel_net


  nginx:
    # image: nginx:1.24.0
    # image: uyinn28/nginx:1.24.0-alpine3.17-otel-v2
    image: uyinn28/nginx:1.21.6-alpine3.15-otel-v2
    # environment:
    #   - OTEL_EXPORTER_OTLP_ENDPOINT="collector:4317"
    volumes:
      # - ./conf.d/nginx/opentelemetry_module.conf:/usr/lib/nginx/modules/otel_ngx_module.so

      # - ./otel_ngx_module-debian-11.3-nginx-1.24.0.so:/opt/modules/otel_ngx_module.so
      - ./conf.d/nginx/otel-nginx.toml:/conf/otel-nginx.toml
      - ./conf.d/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 18080:80
    networks:
      - nginx_otel_net

  server-opentelemetry-01:
    image: uyinn28/server-opentelemetry
    environment:
      AppName: server-opentelemetry-01
      NextServer: http://server-opentelemetry-02
    networks:
      - nginx_otel_net

  server-opentelemetry-02:
    image: uyinn28/server-opentelemetry
    environment:
      AppName: server-opentelemetry-02
      # NextServer: http://server-opentelemetry-02
    networks:
      - nginx_otel_net

networks:
  nginx_otel_net:

